MvcBookStore/Controllers/BookStoreController.cs
using MvcBookStore.Models;
//list
using PagedList;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
namespace MvcBookStore.Controllers
{
    public class BookStoreController : Controller
    {
        //Tao 1 doi tuong chua tona bo CSDL tu dbQLBansach
        QLBANSACHDataContext data = new QLBANSACHDataContext("Data Source=localhost\\SQLEXPRESS01;Initial Catalog=QLBANSACH;Integrated Security=True;Encrypt=False");

        private List<SACH> Laysachmoi()
        {
            //Sap xep giam dan theo Ngaycapnhat , lay gia tri count dong dau
            return data.SACHes.OrderByDescending(a => a.Ngaycapnhat).ToList();
        }
        // GET: BookStore
        public ActionResult Index(int? page, string sortOrder)
        {
            int pageSize = 8;
            int pageNum = (page ?? 1);

            var sach = data.SACHes.AsQueryable(); // Start with all books

            // Add sorting logic
            switch (sortOrder)
            {
                case "price_desc":
                    sach = sach.OrderByDescending(s => s.Giaban);
                    break;
                case "price_asc":
                    sach = sach.OrderBy(s => s.Giaban);
                    break;
                default:
                    sach = sach.OrderByDescending(s => s.Ngaycapnhat); // Default sorting by update date
                    break;
            }

            ViewBag.CurrentSort = sortOrder;
            ViewBag.CurrentPage = pageNum; // Pass the current page to the view

            return View(sach.ToPagedList(pageNum, pageSize));
        }



        //Them chu de voi tung muc nav
        public ActionResult Loai()
        {
            var loai = from cd in data.Loais select cd;
            return PartialView(loai);
        }
        //Them nha xuat ban voi tung muc nav
        public ActionResult Nhaxuatban()
        {
            var nhaxuatban = from nxb in data.NHAXUATBANs select nxb;
            return PartialView(nhaxuatban);
        }
        //Chia san pham theo chu de
        public ActionResult SPTheoloai(int id, int? page)
        {
            //Tao bien quy dinh so san pham tren 1 trang
            int pageSize = 8;
            //Tao bien so trang
            int pageNum = (page ?? 1);
            var sach = from s in data.SACHes where s.MaLoai == id select s;
            return View(sach.ToPagedList(pageNum, pageSize));
        }
        //Chia san pham theo Nha Xuat Ban
        public ActionResult SPTheoNXB(int id, int? page)
        {
            //Tao bien quy dinh so san pham tren 1 trang
            int pageSize = 8;
            //Tao bien so trang
            int pageNum = (page ?? 1);
            var sach = from s in data.SACHes where s.MaNXB == id select s;
            return View(sach.ToPagedList(pageNum, pageSize));
        }
        //Lay thong tin chi tiet sach
        public ActionResult Details(int id)
        {
            var sach = from s in data.SACHes
                       where s.Masach == id
                       select s;
            return View(sach.Single());
        }
        public ActionResult Thoat()
        {
            Session["Taikhoan"] = null;
            return View();
        }
        public ActionResult TimKiem(string search)
        {
            // Thực hiện logic tìm kiếm dựa trên tham số 'search'
            // Ở đây, tôi giả sử bạn muốn tìm kiếm theo Tensach
            var ketQuaTimKiem = data.SACHes.Where(s => s.Tensach.Contains(search)).ToList();

            // Truyền kết quả tìm kiếm đến view
            return View(ketQuaTimKiem);
        }

    }
}

MvcBookStore/Views/BookStore/Details.cshtml
@{
    ViewBag.Title = @Model.Tensach;
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}
<style>
    /* Cho container chính */
    .container {
        margin-top: 20px;
    }

    /* Cho hình ảnh sản phẩm */
    .img-fluid {
        max-width: 100%;
        height: auto;
        border: 1px solid #ddd; /* Viền ảnh */
        border-radius: 8px; /* Bo tròn góc */
    }

    /* Cho thông tin sản phẩm bên phải */
    .col-md-6 {
        display: flex;
        flex-direction: column;
        justify-content: center;
    }

    /* Cho các thông tin sản phẩm */
    h3 {
        color: #333;
        font-size: 28px;
    }

    p {
        color: #555;
        font-size: 16px;
        margin-bottom: 10px;
    }

    /* Giá bán đặc biệt được đặt màu đỏ và làm đậm */
    .text-danger {
        color: #d9534f;
        font-weight: bold;
    }

    /* Nút Đặt Mua và Hết Hàng */
    .text-center {
        margin-top: 20px;
    }

    .btn {
        cursor: pointer;
    }

    /* Nút Đặt Mua màu xanh dương */
    .btn-primary {
        background-color: #428bca;
        color: #fff;
    }

        .btn-primary:hover {
            background-color: #3071a9;
        }

    /* Nút Hết Hàng màu đỏ */
    .btn-danger {
        background-color: #d9534f;
        color: #fff;
    }

        .btn-danger:hover {
            background-color: #c9302c;
        }

</style>
<div class="container mt-5">
    <div class="row">
        <div class="col-md-6">
            <img class="img-fluid" src="~/images/anhsp/@Model.Anhbia" alt="@Model.Tensach">
        </div>
        <div class="col-md-6">
            <h3>@Model.Tensach</h3>
            <p>Loại sách: @Model.Loai.TenLoai</p>
            <p>Nhà Xuất Bản: @Model.NHAXUATBAN.TenNXB</p>
            <p class="text-danger">Giá bán: @String.Format("{0:#,##0}", @Model.Giaban) VNĐ</p>
            <p>Số lượng tồn: @Model.Soluongton quyển</p>
            <p>Mô tả: @Model.Mota</p>

            @if (@Model.Soluongton != 0 && @Model.Soluongton != null)
            {
                <div class="text-center">
                    <a class="btn btn-primary" href="@Url.Action("ThemGiohang","GioHang", new {@iMasach=@Model.Masach,@strURL=Request.Url.ToString()})">Đặt Mua</a>
                </div>
            }
            else
            {
                <div class="text-center">
                    <button type="button" class="btn btn-danger" disabled>Hết Hàng!</button>
                </div>
            }
        </div>
    </div>
</div>

MvcBookStore/Views/BookStore/Index.cshtml
@using MvcBookStore.Models
@using PagedList.Mvc;
@using System.Web.Mvc

<!-- Các đoạn mã khác trong file Razor -->

@model PagedList.PagedList<SACH>
<style>
    .Trang li {
        display: inline;
        letter-spacing: 10px;
    }
</style>
@{
    ViewBag.Title = "Cửa Hàng Bán Sách";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}
<h3 class="text-center">Sách mới cập nhật</h3>
<div class="row">
    @foreach (var sach in Model)
    {
        <div class="col-xl-3 col-lg-4 col-md-4 col-12">
            <div class="single-product">
                <div class="product-img">
                    <a href="@Url.Action("Details", "BookStore", new {id=sach.Masach})">
                        <img class="default-img" src="~/images/anhsp/@sach.Anhbia" alt="#">
                        <img class="hover-img" src="~/images/anhsp/@sach.Anhbia" alt="@sach.Tensach">
                    </a>
                    <div class="button-head">
                        <div class="product-action">
                            <a href="@Url.Action("Details", "BookStore", new {id=sach.Masach})" title="Thông tin chi tiết"><i class="ti-eye"></i><span>Xem nhanh</span></a>
                            <a title="Wishlist" href="@Url.Action("ThemYeuThich","YeuThich", new {@iMasach=@sach.Masach,@strURL=Request.Url.ToString()})"><i class=" ti-heart "></i><span>Thêm vào yêu thích</span></a>
                        </div>
                        <div class="product-action-2">
                            @if (@sach.Soluongton != 0 && @sach.Soluongton != null)
                            {
                                <a href="@Url.Action("ThemGiohang","GioHang", new {@iMasach=@sach.Masach,@strURL=Request.Url.ToString()})">Thêm vào giỏ</a>
                            }
                        </div>
                    </div>
                </div>
                <div class="product-content text-center">
                    <h3><a href="@Url.Action("Details", "BookStore", new {id=sach.Masach})">@sach.Tensach</a></h3>
                    <div class="product-price">
                        @if (@sach.Soluongton != 0 && @sach.Soluongton != null)
                        {
                            <span>@String.Format("{0:#,##0}", @sach.Giaban)</span><span> VNĐ</span>
                        }
                        else
                        {
                            <span>Hết Hàng</span>
                        }
                    </div>
                </div>
            </div>
        </div>
    }
</div>
<div class="Trang">
    Trang @(Model.PageNumber < Model.PageCount ? Model.PageNumber : Model.PageCount) / @Model.PageCount
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page, sortOrder = ViewBag.CurrentSort }))
</div>

MvcBookStore/Views/BookStore/Loai.cshtml
@model IEnumerable<MvcBookStore.Models.Loai>
<li>
    <a href="#">Thể Loại<i class="ti-angle-down"></i></a>
    <ul class="dropdown">
        @foreach (var item in Model)
        {
            
            <li><a href="@Url.Action("SPTheoloai","BookStore",new {id=item.MaLoai})" class="list-group-item">@item.TenLoai</a></li>
            
        }
    <br/>
    </ul>
</li>

MvcBookStore/Views/BookStore/Nhaxuatban.cshtml
@model IEnumerable<MvcBookStore.Models.NHAXUATBAN>
<li>
    <a>Nhà Xuất Bản<i class="ti-angle-down"></i></a>
    <ul class="dropdown">
        @foreach (var item in Model)
        {
            <li><a href="@Url.Action("SPTheoNXB","BookStore",new {id=item.MaNXB})" class="list-group-item">@item.TenNXB</a></li>
        }
    <br/>
    </ul>
</li>

MvcBookStore/Views/BookStore/SPTheoNXB.cshtml
@using MvcBookStore.Models
@using PagedList.Mvc;
@model PagedList.PagedList<SACH>

<style>
    .Trang li {
        display: inline;
        letter-spacing: 20px;
    }

    .Trang a:active {
        background-color: green;
        text-decoration-color: green;
    }
</style>
@{
    ViewBag.Title = "Sách Theo Nhà Xuất Bản Trang"+ @Model.PageNumber;
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}
<h3 class="text-center">Sách theo Nhà Xuất Bản</h3>
<div class="row">
    @foreach (var sach in Model)
    {
        <div class="col-xl-3 col-lg-4 col-md-4 col-12">
            <div class="single-product">
                <div class="product-img">
                    <a href="@Url.Action("Details", "BookStore", new {id=sach.Masach})">
                        <img class="default-img" src="~/images/anhsp/@sach.Anhbia" alt="#">
                        <img class="hover-img" src="~/images/anhsp/@sach.Anhbia" alt="@sach.Tensach">
                    </a>
                    <div class="button-head">
                        <div class="product-action">
                            <a href="@Url.Action("Details", "BookStore", new {id=sach.Masach})" title="Thông tin chi tiết"><i class="ti-eye"></i><span>Xem nhanh</span></a>
                            <a title="Wishlist" href="@Url.Action("ThemYeuThich","YeuThich", new {@iMasach=@sach.Masach,@strURL=Request.Url.ToString()})"><i class=" ti-heart "></i><span>Thêm vào yêu thích</span></a>
                        </div>
                        <div class="product-action-2">
                            @if (@sach.Soluongton != 0 && @sach.Soluongton != null)
                            {
                                <a href="@Url.Action("ThemGiohang","GioHang", new {@iMasach=sach.Masach,@strURL=Request.Url.ToString()})">Thêm vào giỏ</a>
                            }
                        </div>
                    </div>
                </div>
                <div class="product-content text-center">
                    <h3><a href="@Url.Action("Details", "BookStore", new {id=sach.Masach})">@sach.Tensach</a></h3>
                    <div class="product-price">
                        @if (@sach.Soluongton != 0 && @sach.Soluongton != null)
                        {
                            <span>@String.Format("{0:#,##0}", @sach.Giaban)</span><span> VNĐ</span>
                        }
                        else
                        {
                            <span>Hết Hàng</span>
                        }
                    </div>
                </div>
            </div>
        </div>
    }
</div>
<div class="Trang">
    Trang @(Model.PageCount<Model.PageNumber?0:Model.PageNumber)/@Model.PageCount
    @Html.PagedListPager(Model, page => Url.Action("SPTheoNXB", new { page = page }))
</div>  

MvcBookStore/Views/BookStore/SPTheoloai.cshtml
@using MvcBookStore.Models
@using PagedList.Mvc;
@model PagedList.PagedList<SACH>

<style>
    .Trang li {
        display: inline;
        letter-spacing: 20px;
    }
    .Trang a:active {
        background-color: green;
        text-decoration-color: green;
    }
</style>
@{
    ViewBag.Title = "Sách Theo Loại Trang "+ @Model.PageNumber;
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}
<h3 class="text-center">Sách xếp theo loại</h3>
<div class="row">
    @foreach (var sach in Model)
    {
        <div class="col-xl-3 col-lg-4 col-md-4 col-12">
            <div class="single-product">
                <div class="product-img">
                    <a href="@Url.Action("Details", "BookStore", new {id=sach.Masach})">
                        <img class="default-img" src="~/images/anhsp/@sach.Anhbia" alt="#">
                        <img class="hover-img" src="~/images/anhsp/@sach.Anhbia" alt="@sach.Tensach">
                    </a>
                    <div class="button-head">
                        <div class="product-action">
                            <a href="@Url.Action("Details", "BookStore", new {id=sach.Masach})" title="Thông tin chi tiết"><i class="ti-eye"></i><span>Xem nhanh</span></a>
                            <a title="Wishlist" href="@Url.Action("ThemYeuThich","YeuThich", new {@iMasach=@sach.Masach,@strURL=Request.Url.ToString()})"><i class=" ti-heart "></i><span>Thêm vào yêu thích</span></a>
                        </div>
                        <div class="product-action-2">
                            @if (@sach.Soluongton != 0 && @sach.Soluongton != null)
                            {
                                <a href="@Url.Action("ThemGiohang","GioHang", new {@iMasach=@sach.Masach,@strURL=Request.Url.ToString()})">Thêm vào giỏ</a>
                            }
                        </div>
                    </div>
                </div>
                <div class="product-content text-center">
                    <h3><a href="@Url.Action("Details", "BookStore", new {id=sach.Masach})">@sach.Tensach</a></h3>
                    <div class="product-price">
                        @if (@sach.Soluongton != 0 && @sach.Soluongton != null)
                        {
                            <span>@String.Format("{0:#,##0}", @sach.Giaban)</span><span> VNĐ</span>
                        }
                        else
                        {
                            <span>Hết Hàng</span>
                        }
                    </div>
                </div>
            </div>
        </div>
    }
</div>
<div class="Trang">
    Trang @(Model.PageCount<Model.PageNumber?0:Model.PageNumber)/@Model.PageCount
    @Html.PagedListPager(Model, page => Url.Action("SPTheoloai", new { page = page }))
</div>

MvcBookStore/Views/BookStore/SachGiaGiam.cshtml
@model PagedList.IPagedList<MvcBookStore.Models.SACH>
@using PagedList.Mvc

@{
    ViewBag.Title = "Sắp xếp đơn giá giảm dần";
}

<div class="container">
    @foreach (var item in Model)
    {
        <div>
            <h2>@item.Tensach</h2>
            <p>Giá: @string.Format("{0:C}", item.Giaban)</p>
        </div>
    }

    @Html.PagedListPager(Model, page => Url.Action("SachGiaGiam", new { page }))
</div>

MvcBookStore/Views/BookStore/Thoat.cshtml
@{
    ViewBag.Title = "Đăng Xuất";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<style>
    body {
        background-color: #f8f9fa; /* Màu nền trang */
        font-family: 'Arial', sans-serif; /* Font chữ chính */
    }

    .container {
        margin-top: 50px; /* Khoảng cách từ đỉnh trang đến nội dung */
        text-align: center; /* Canh giữa nội dung */
    }

    h4 {
        color: #28a745; /* Màu văn bản cho thông báo thành công */
        margin-bottom: 20px; /* Khoảng cách từ thông báo đến nút "Về Trang Chủ" */
    }

    h5 {
        margin-top: 20px; /* Khoảng cách từ thông báo đến nút "Về Trang Chủ" */
    }

    .btn-primary {
        padding: 10px 20px; /* Kích thước nút */
        font-size: 18px; /* Kích thước chữ nút */
    }
</style>

<div class="container">
    <h4>Đã đăng xuất! <br />Xin cảm ơn @Session["TDN"].ToString() đã truy cập! </h4>
    <h5 class="text-primary">
        @Html.ActionLink("Về Trang Chủ", "Index", "BookStore", new { @class = "btn btn-primary", style = "color: white;" })
    </h5>
</div>

MvcBookStore/Views/BookStore/TimKiem.cshtml
@using MvcBookStore.Models
@model List<SACH>

@{
    ViewBag.Title = "Kết Quả Tìm Kiếm";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<h2>Kết Quả Tìm Kiếm</h2>

@if (Model != null && Model.Any())
{
    <div class="row">
        @foreach (var sach in Model)
        {
            <div class="col-xl-3 col-lg-4 col-md-4 col-12">
                <div class="single-product">
                    <div class="product-img">
                        <a href="@Url.Action("Details", "BookStore", new {id=sach.Masach})">
                            <img class="default-img" src="~/images/anhsp/@sach.Anhbia" alt="#">
                            <img class="hover-img" src="~/images/anhsp/@sach.Anhbia" alt="@sach.Tensach">
                        </a>
                        <div class="button-head">
                            <div class="product-action">
                                <a href="@Url.Action("Details", "BookStore", new {id=sach.Masach})" title="Thông tin chi tiết"><i class="ti-eye"></i><span>Xem nhanh</span></a>
                                <a title="Wishlist" href="@Url.Action("ThemYeuThich","YeuThich", new {@iMasach=@sach.Masach,@strURL=Request.Url.ToString()})"><i class=" ti-heart "></i><span>Thêm vào yêu thích</span></a>
                            </div>
                            <div class="product-action-2">
                                @if (@sach.Soluongton != 0 && @sach.Soluongton != null)
                                {
                                    <a href="@Url.Action("ThemGiohang","GioHang", new {@iMasach=@sach.Masach,@strURL=Request.Url.ToString()})">Thêm vào giỏ</a>
                                }
                            </div>
                        </div>
                    </div>
                    <div class="product-content text-center">
                        <h3><a href="@Url.Action("Details", "BookStore", new {id=sach.Masach})">@sach.Tensach</a></h3>
                        <div class="product-price">
                            @if (@sach.Soluongton != 0 && @sach.Soluongton != null)
                            {
                                <span>@String.Format("{0:#,##0}", @sach.Giaban)</span><span> VNĐ</span>
                            }
                            else
                            {
                                <span>Hết Hàng</span>
                            }
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
}
else
{
    <p>Không có kết quả tìm kiếm.</p>
}